json.id(rental.id)
json.book_id(rental.book_id)
json.user_id(rental.user_id)
json.checkout_date(rental.checkout_date)
json.return_due_date(rental.return_due_date)
json.return_date(rental.return_date)
json.return_approver(rental.return_approver)
