json.id(rental.id)
json.book_id(rental.book_id)
json.user_id(rental.user_id)
json.content(rental.content)
json.point(rental.point)
json.created_at(rental.created_at)
json.updated_at(rental.updated_at)
