json.id(review.id)
json.book_id(review.book_id)
json.user_id(review.user_id)
json.content(review.content)
json.point(review.point)
json.created_at(review.created_at)
json.updated_at(review.updated_at)
